version: 2

jobs:
  build:
    docker:
      - image: alpine:latest

    working_directory: ~/TESOFFICIAL

    steps:
      - run: apk -U -q --no-cache --no-progress add git tidyhtml
      - checkout
